language: python
sudo: false
cache: pip

matrix:
  include:
    - os: linux
      python: 3.6
      language: python

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install pyqt5 pytest pyinstaller

script:
  - python3 -m pytest -vv test_kalkulacka/
  - pyinstaller __main__.py -n kalkulacka-app
      --exclude-module tkinter
      --add-data kalkulacka:kalkulacka
      -F -w

deploy:
    provider: releases
    api_key:
        secure: DHZig9dr062EAGWaiQ9D/cc1E66sMzbMNgfei1MmCaaTBbbZGxKmDV4My99zeNeaysYFR4/tCz3Yt3F4jQH0OofIakmu+8MBlQxU6nNfFmDUc13f//HaYBm5sZzMjjV76UiEmMI2aIJbrEDWoMw7GbT78v6YqjQ/0TUJCBvweUPuMntLqAUDzxOsjUziXjo/zT3p63F2f5GhsorRfvhHGfVi7Mcp+KzLXUqKnoxtbB+PkrVQsOJZABcA/n55VasWuE3HwNhFY3ZyinJWl0Zg0TVnFLVelazCKBaVSq/wYSJe4nHGxCGSxlp5StDl0W4NAU61dW/YYYruM8/IiQoHdEAkHy9508ZVsMGq38YxqA5TmD8/v4LBuGlY/TxNJEPs4Sh/hkY4rfUDZBWyCKakmqj/vfIEa7XmXapl4cl6dUc094SlvJwP28Psm/BTkUXKKlLaRFPpL01P0vZQBqWPz8+ZAyeAfPu6aHh0Fpb4N79FW2rQaEKGlGb68VXoS2bAd+yr6RlVDIpSo/st5G3qDdtShobm3v8vEqPQWUErQtf8BFRnjZRwabQekUJnSpAxVzSiaSUtpdDLADzzaLPtZMlhhso8UNefs0TOUFY+j/IvkB3HfjnaEfuQadmoG5mubmVlldW/Zt8iSI7liboKC4qTf+XQ6lcBBjhsgOddiZ8=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
        tags: true