language: python
sudo: false
cache: pip

matrix:
  include:
    - os: linux
      python: 3.6
      language: python
    - os: osx
      language: generic

install:
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
        brew install python3
    fi
  - python3 -m pip install --upgrade pip
  - python3 -m pip install pyqt5 pytest pyinstaller

script:
  - python3 -m pytest -vv test_kalkulacka/
  - pyinstaller __main__.py -n kalkulacka-app
      --exclude-module tkinter
      --add-data kalkulacka:kalkulacka
      -F -w
  - |
    if [[ "$(uname -s)" == 'Darwin' ]]; then
        zip -r dist/kalkulacka-app.app.zip dist/kalkulacka-app.app
        rm -rvf dist/kalkulacka-app.app
    fi
  - for f in $(ls dist); do mv dist/$f dist/$(uname -s)-$f; done

deploy:
    provider: releases
    api_key:
        secure: IzoWZfb7ciMOpZkMZRTjRv6QzaW4lnxqxT/CxnXk7wAM0Z9KE2s/fp2F73bYlnGiHw2hARVoQD+PjiLB/2Ry/r4FCTHgP7Z6hllLsIlX6iX6fei2cM/MUCck4r98FBy55dvs2RgJLJ3io9Fz0oASAccpr6Sn/35wTRnu+TYrSi7uvpaxY91niKAPw+lmjwht3Qj3Pb0eCh3eUNuUU61tp2UxWntfsD8aQyP8CLIf4VJd5BxBiKTF94cxpL/cv0jbLOWf/o8xLRJXZDYABW22Zx458Ck8GW4gebumDI/DEB/EaAnFN9ZfUZqxVxtz8pKd5TTdNBOqXxmeLSxBwbe2bi4ctATJ4x3D5pyWP3Hau4/CK7d9tEiqMndPhEgOXKrU0T40lZ6CuOb86E1lkawX6uAkOsEjqd/K7nys1ZmfoNWWfU0aexqmsbd2DBT8Ak/RVc99gDIurkb6QV4O/6f+FheGvFORRRLMp0sa7/wY+3POs3Bo27Uh/vhyLkCm0w8Zh77WuhCZBBxWJOH9PLY0julAcfR+F8M3/M6tNKYYQu8HFehjp31/+6PJGZF/uoAmGX9ZXgS6ymyuQ74nRmvwcTHXlFnmY49I83v5zd6pz+6lSLWGrpVEJobV78m8wV+od3U4eVkNzrn39lSxiDZV4aFOO81gCoRXG2Gp4A0Pnb4=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
        tags: true